services:
  webssh:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      # HTTPS
      - "traefik.http.routers.webssh.rule=Host(`webssh.local`)"
      - "traefik.http.routers.webssh.entrypoints=websecure"
      - "traefik.http.routers.webssh.tls=true"
      - "traefik.http.services.webssh.loadbalancer.server.port=3000"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.webssh-redirect.rule=Host(`webssh.local`)"
      - "traefik.http.routers.webssh-redirect.entrypoints=web"
      - "traefik.http.middlewares.webssh-https.redirectscheme.scheme=https"
      - "traefik.http.routers.webssh-redirect.middlewares=webssh-https"
    networks:
      - traefik

networks:
  traefik:
    external: true
